#!/bin/sh

#########
# USAGE #
#########
# The program always makes normal output first, and visualizes it, unless it
# is specified otherwise
# Parameters:
#   -r      Reachability plot
#   -R      Reachability plot, but don't run the normal algorithm
#   -q      Quality measure
#   -Q      Quality measure, ran over the output file (the output file (.out) should exist!)
#   -t      Time algorithm (cannot be used in combination with -R)
#   -nv     Run visualization, but do not display the image
#   -no     Do not run a real algorithm.

export r="-r"
# parameters
export params="-nl -q -t $r"

# run on the folder specified

for f in $*
do
    if [ $(echo "$f" | awk -F . '{print $NF}') != "out" ]; then
        if [ $(echo "$f" | awk -F . '{print $NF}') != "png" ]; then
            echo "./cluster $params $f"
            ./cluster $params $f
            cp output.png $f.out.png
            if [ "$r" = "-r" ]; then
                cp reach.png $f.reach.png
           fi
        fi
    fi
done
