#!/bin/sh

# first compile all files

./cluster

java generator.Main > input/$1

cat input/$1 | java Main allnoise > input/$1.out

# visualization

cat input/$1.out | java visualize.Main

xdg-open output.png
