#!/bin/sh

# first compile all files

javac Main.java algorithm/*.java generator/*.java model/*.java quality/*.java visualize/*.java

cat $1 | java Main > $1.out

# visualization

cat $1.out | java visualize.Main

xdg-open output.png
